services:
  db:
    image: postgres:16
    container_name: autoharbour_db
    restart: always
    environment:
      POSTGRES_USER: autoharbour
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: autoharbour
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
